### ISSUE TITLE
Title tag does not work

### ISSUE THREAD

**Issue by Genius398** [Educational-Websites/Live-Code-Editor#11]
Title tag does not work

**Comment by Genius398** [comment]
@Educational-Websites/contributor-discussions

**Comment by e-coders** [comment]
Ok. but there its a IFrame tag - In that Iframe tag it shows the content! If there I adds a button that hides all the Textareas from the page so its also Hidded from the Iframe but If I adds it in a Iframe so It can't overwrite the page content.

**Comment by Genius398** [comment]
> Ok. but there its a IFrame tag - In that Iframe tag it shows the content! If there I adds a button that hides all the Textareas from the page so its also Hidded from the Iframe but If I adds it in a Iframe so It can't overwrite the page content.

ok

**Comment by e-coders** [comment]
Wait...sharing a file

**Comment by e-coders** [comment]
Working for me. What's for you?
Try checking the editor like you're typing in CSS Editor but HTML Editor can show HTML and if you're including the <script> or <style> tag so it works same as CSS/JavaScript. Check the editor, CSS if the display is none, check all errors.

**Comment by Genius398** [comment]
No. I think i got this

**Comment by Genius398** [comment]
no i dint
