### ISSUE TITLE
Get some sample/starter code

### ISSUE THREAD

**Issue by Genius398** [Educational-Websites/Live-Code-Editor#18]
**Describe your feature here**
I've been thinking of this for a while, but if we make a button, which when clicked, can load some sample code. Like, it can load:

1. The HTML, HEAD, TITLE, BODY, DIV, and H1 tags
2. It can give the tags proper ids 
3. It can give appropriate styling to the tags in CSS.
4. It can have a button with an onclick() function. When clicked, it will load an alert

**Comment by somePythonProgrammer** [comment]
#### I've mentioned that in one issue/discussion, but unfortunately, I don't remember which one.
We can add a 'request' feature to our live code editor, and make a link here.
A request would look like this: (javascript)
`
window.location.replace('https://educational-websites.github.io/Live-Code-Editor?template=example1')
`
I mean the part after the ?

**Comment by somePythonProgrammer** [comment]
@Genius398 I just need to figure out how to implement that, then we can store the examples in a json file and retrieve them!

**Comment by Genius398** [comment]
ok.. but idk much about json

**Comment by Genius398** [comment]
Maybe @e-coders can help. The same way he cleared, we can add

**Comment by Genius398** [comment]
i might be able to do this

**Comment by Genius398** [comment]
YAAYYYYYY WWWOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO

**Comment by Super45coder** [comment]
YEAH!
________________________________
