### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by e-coders** [Educational-Websites/Live-Code-Editor#60]
While Using Sample Code, my InnerHTML Property can't do anything and occurs an error. So we'll remove the JavaScript code or change it then we'll need to Fix the Our site Console that After Fixing Our issue, it will also Show that error and 1 error per time. So we need to fix these 2 things and also that We'll need to Remove the "onkeyup" Property from HTML and change it to Forever as we can to automatically Per Every Mili-seconds, view if there have errors in code and then Show them in console and when fixed, Forever will also hides because no errors.

**Comment by Genius398** [comment]
ITs working
